config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations', confirmations: 'users/confirmations' }
  get 'likes/new'
  get 'likes/create'
  
  root 'users#index'
  resources :users, only: %i[index show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: %i[new create]
    end
  end

  post "users/:id/generate_token" => "users#generate_token", as: :generate_token

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users, only: [] do
        resources :posts, only: [:index, :create] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'user_id'
  has_many :comments, foreign_key: 'user_id'

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  before_validation :set_default_posts_counter, on: :create

  validates :role, inclusion: { in: %w[admin user], message: 'Invalid role' }

  def admin?
    role == 'admin'
  end

  def most_recent_posts(limit = 3)
    posts.order(created_at: :desc).limit(limit)
  end

  def generate_token
    self.token = SecureRandom.base58(30)
  end

  private

  def set_default_posts_counter
    self.posts_counter ||= 0
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  def create
    user = User.find_by(email: params[:user][:email])
    if user && !user.confirmed?
      user.confirm
      sign_in(user)
      redirect_to users_path
    else
      redirect_to new_user_confirmation_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find_by_id(params['id'])
  end

  def generate_token
    @user = User.find(current_user.id)
    @user.generate_token
    if @user.save
      flash[:success] = 'Token generated successfully'
    else
      flash[:error] = @user.errors.full_messages.join(', ')
    end
    redirect_to user_path(@user)
  end
end

app/views/users/index.html.erb
<h1 class='blog-header'>The Normal Blog</h1>

<div class='user-container'>
  <%= link_to 'Sign In', new_user_session_path %>
    <% @users.each do |user| %>
      <div class="user-intro"> 
        <div class="user-img">
          <img src="<%= user.photo if user.photo %>" alt="user photo">
        </div>

        <div class="user-info">
          <h2><%= link_to user.name, user_path(user), id: "user_#{user.id}" %></h2>
          <h3>Number of Posts: <%= user.posts_counter %></h3>
        </div>
      </div>
    <% end %>
</div>

app/views/users/show.html.erb
<div class='user-container'>
    <%= link_to 'Sign Out', destroy_user_session_path %>
      <div class="user-intro"> 
        <div class="user-img">
          <img src="<%= @user.photo %>" alt="user photo">
        </div>

        <div class="user-info">
          <h2><%= @user.name %></h2>
          <h3>Number of Posts: <%= @user.posts_counter %></h3>
        </div>
        <% if @user == current_user %>
        <div class="api-section">
          <%= button_to "generate token", generate_token_path, class:"button" %>
          <%= "API_Token: #{@user.token}" %>
        </div>
      <%end%>
      </div>
</div>

<div class="user-bio">
  <h2>Bio</h2>
  <p><%= @user.bio %></p>
</div>

<div class="user-posts">
  <h2>Most Recent Posts</h2>
  <% @user.most_recent_posts(3).each do |post| %>
    <div class="post">
      <h3><%= link_to post.title, user_post_path(@user, post), id: "post_#{post.id}" %></h3>
      <p><%= post.text %></p>

      <div class="likes-comments">
        <span>Comments: <%= post.comments_counter %></span><br/>
        <span>Likes: <%= post.likes_counter %></span>
      </div>
    </div>
  <% end %>
</div>

<button>
  <%= link_to 'More Posts',  user_posts_path(@user) %>
</button>

app/views/users/show_users.html.erb
<h1>This is the first user. Aemond Targaryen</h1>