config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations', confirmations: 'users/confirmations' }
  get 'likes/new'
  get 'likes/create'
  
  root 'users#index'
  resources :users, only: %i[index show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: %i[new create]
    end
  end

  post "users/:id/generate_token" => "users#generate_token", as: :generate_token

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users, only: [] do
        resources :posts, only: [:index, :create] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'author_id'
  has_many :likes, foreign_key: 'post_id', dependent: :destroy
  has_many :comments, foreign_key: 'post_id', dependent: :destroy

  validates :title, presence: true, length: { maximum: 250 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def most_recent_comments(limit = 5)
    comments.order(created_at: :desc).limit(limit)
  end

  after_create :increment_posts_counter
  after_destroy :decrement_posts_counter

  private

  def increment_posts_counter
    user&.increment!(:posts_counter) if user.present?
  end

  def decrement_posts_counter
    user&.decrement!(:posts_counter) if user.present?
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  before_action :set_user, only: %i[create]
  load_and_authorize_resource

  def index
    @posts = User.find(params[:user_id]).posts.includes(:comments)
    render json: @posts
  end

  def create
    @post = @user.posts.build(post_params)

    if @post.save
      render json: @post, status: :created
    else
      render json: { errors: @post.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private

  def set_user
    return if request.headers['Authorization'].nil?

    token = request.headers['Authorization'].split.last
    @user = User.find_by(token:)
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/post_controller.rb
class PostsController < ApplicationController
  def index; end

  def show; end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:success] = 'Post deleted successfully'
    else
      flash[:error] = 'Error: Post could not be deleted'
    end
    redirect_to user_posts_path(current_user)
  end

  def show
    @post = Post.find_by_id(params[:id])
    @comment = Comment.all
    @user = User.find_by_id(params[:user_id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    @post.likes_counter = 0
    @post.comments_counter = 0

    if @post.save
      redirect_to user_post_path(current_user, @post)
    else
      render :new, alert: 'Post not created'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/views/posts/index.html.erb
<div class='user-container'>
  <div class="user-intro"> 
    <div class="user-img">
      <img src="<%= @user.photo %>" alt="user photo">
    </div>

    <div class="user-info">
      <h2><%= @user.name %></h2>
      <h3>Number of Posts: <%= @user.posts_counter %></h3>
    </div>
  </div>
</div>

<h1>New Posts</h1>

<div class="new-post">
  <%= link_to 'Add a new post', new_user_post_path(user_id: @user.id) %>
</div>

<div class="user-posts">
  <h2>Posts</h2>
  <% @user.posts.each do |post| %>
    <div class="post">
      <h3><%= link_to post.title, user_post_path(@user, post) %></h3>
      <p><%= post.text %></p>
      <div class="likes_comments">
        <span>Likes: <%= post.likes_counter %></span><br/>
        <span>Comments: <%= post.comments_counter %></span>
      </div>

      <div class="user-comments">
        <h2>Comments</h2>
        <% post.most_recent_comments(5).each do |comment| %>
          <div class="comment">
            <p>Username: <%= comment.Text %></p>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
  <%= link_to 'Pagination', user_posts_path(@user), class: 'button' %>
</div>

app/views/posts/new.html.erb
<div class="new-post-container">
  <h1>Add a new post</h1>

  <%= form_with model: @post, url: user_posts_path do |form| %>
    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>

    <div class="field">
      <%= form.label :text %>
      <%= form.text_area :text %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="post-page">
  <div class="post">
    <h3><%= @post.title %> by <%= @user.name %></h3>
    <p><%= @post.text %></p>
    <div class="likes_comments">
      <span>Likes: <%= @post.likes_counter %></span><br/>
      <span>Comments: <%= @post.comments_counter %></span>
      <span><%= button_to 'Delete Post :memo:', user_post_path(@user, @post), method: :delete, class: 'button' if can? :destroy, @post %></span>
    </div>

    <div class="user-comments">
      <h2>Comments</h2>
      <% @post.comments.each do |comment| %>
        <div class="comment">
          <p>Username: <%= comment.Text %></p>
          <p><%= button_to 'Delete Comment :speech_balloon:', user_post_comment_path(@user, @post, comment), method: :delete, class: 'button' if can? :destroy, comment %></p>
        </div>
      <% end %>
    </div>

    <div class="new-comment-like">
      <%= form_with model: @like, url:user_post_likes_path(post_id: @post.id) do |like| %>
        <%= like.submit  "Like", class:"new-post-btn submit-btn"%>
      <% end %>
  
      <%= link_to 'Add A New comment', new_user_post_comment_path(user_id: @post.author_id, post_id: @post.id), class: 'submit-btn' %>
    </div>
  </div>
</div>